name: generate-snake-game-from-github-contribution-grid

on:
  schedule:
    # Run every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions: 
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Generate the snake SVG and GIF
      - name: Generate Snake
        uses: Platane/snk@v3.0.0
        with:
          github_user_name: sanayamahajan-23
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=blue
            dist/github-contribution-grid-snake-light.svg?palette=github-light&color_snake=green
            dist/github-contribution-grid-snake.gif?palette=github-dark&color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      # Show the status of the repository (optional for debugging)
      - run: git status

      # Push changes to the repository
      - name: Push changes
        uses: github-actions-x/commit@v4.13.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


