name: Generate Snake

on:
  schedule:
    # Run every 6 hours
    - cron: "0 */6 * * *"

  # Allow manual trigger from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Generate the snake SVG
      - uses: Platane/snk@v2.1.0
        with:
          github_user_name: sanayamahajan-23

      # Show the status of the repository (optional for debugging)
      - run: git status

      # Push changes to the repository
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


